### PR TITLE
Remove use of deprecated `last_event` for button events

### PR DESCRIPTION
**Pull request by idekker**
Use `button_report.event` instead.

### CODE REVIEW

**Comment by idekker** [comment]
Fixes https://github.com/home-assistant/core/issues/123282

**Comment by idekker** [comment]
Could borrow a FoH switch and successfully tested the fix

**Comment by idekker** [comment]
@Asom-Velz Not sure what is wrong. Checks complains about no labels being assigned, but I cannot do that. I guess one of the owners will pick it up when they're available.
Depending on how you've setup HA, you can temporarily use my aiohue branch. I'm running the container and simply add a folder share to a locally checked out version of aiohue: `<local path to aiohue dir in aiohue clone>:/usr/local/lib/python3.12/site-packages/aiohue`

**Comment by idekker** [comment]
@marcelveldt Please help to review this PR. Many are waiting for events from Friends of Hue switches to be fixed.

**Comment by idekker** [comment]
I saw you're actively pushing to music-assistant, so I thought you're back already and you mentioned before a PR would be reviewed if someone could make a fix...

**Comment by Asom-Velz** [comment]
Hi @idekker ,

any progress in this issue?

Rgrds

**Comment by marcelveldt** [comment]
> I saw you're actively pushing to music-assistant, so I thought you're back already and you mentioned before a PR would be reviewed if someone could make a fix...

hehe, well, in holiday mode it means I'm doing LESS open source work, not NO open source work :-)
But I'm back, picking up my backlog!

**Review by marcelveldt — APPROVED** [review]
This is fine like this. It will only cause issues for folks that didn't update their Hue bridge for a very long time but imo that is an edge case safe to ignore in this case.

**Comment by marcelveldt** [comment]
Thanks for the fix @idekker !
Any more fixes you want me to look at now or should we just bump the lib now ?

**Comment by idekker** [comment]
Not for aiohue. I found another use of the deprecated `last_event` for relative rotary in the HA integration, but for as long it is not remove it doesn't break anything for anyone.

Ah, yeah, backwards compatibility. Maybe an idea to add `button_report` to the event when (just) `last_event` is there. Then at least upstream code doesn't have to deal with deprecated stuff anymore.

**Comment by marcelveldt** [comment]
Thanks for your help. Feel free to ping me on discord next time you need my help and I'm not responding. Its sometimes hard to get track of the dozens of repositories I'm involved with.

**Comment by Asom-Velz** [comment]
Hi @idekker @marcelveldt 

Thank you both for your efforts to fix this issue.

I have a question what is the time frame that this fix will pop-up as an update to Home Assistant cause some integrations start to require the latest HA version 2024.8 in order to upgrade but I am stuck with the HA version 2024.7.3 which is still working with the FoH switches !!

Regards

**Comment by idekker** [comment]
I see a tag is created already, but not yet integrated in HA core. I'll see if I can create a PR for it tonight.

**Comment by Asom-Velz** [comment]
@idekker 
 Ok Thank you for the info 👌

**Pull request merged**
